name: nnti-project
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - pytorch 
  - torchvision 
  - torchaudio
  - transformers
  - sentencepiece 
  - pytorch-cuda=11.8
  - matplotlib
  - pandas
  - datasets
  - numpy
  - notebook
  - protobuf
  - accelerate
  - h5py
